# -*- coding: utf-8 -*-
"""re4car_ani.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zoFcUiD9Oes31eNh5MaMIFeTR5AIuBBd
"""

# Q-learning 자율주행 예제(이전 코드) + 궤적 애니메이션 시각화

import numpy as np
import random
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# 상태 및 행동 공간
state_space = np.linspace(-1.0, 1.0, 11)
action_space = [-1, 0, 1]
q_table = np.zeros((len(state_space), len(action_space)))

# 하이퍼 파라미터
alpha = 0.1
gamma = 0.9
epsilon = 1.0
episodes = 300

# 함수 정의
def get_state_index(position):
    return np.argmin(np.abs(state_space - position))

def get_reward(position):
    return 1.0 - abs(position)

def stepFunc(position, action):
    position += action * 0.1
    position = np.clip(position, -1.0, 1.0)
    reward = get_reward(position)
    return position, reward

# 학습 루프
reward_list = []
trajectories = []  # 에이전트 궤적 저장. 애니메이션 시각화를 위한 핵심 요소
# 학습 도중의 에이전트 위치 변화 궤적을 저장하기 위해 사용
# 왜 필요한가? 애니메이션을 만들기 위해서는 "시간 흐름에 따라 위치가 어떻게 바뀌었는지"를 알아야 함.
# 이를 위해 각 에피소드마다 에이전트가 이동한 위치들을 리스트에 저장한다.
# trajectories = [
#     [0.3, 0.2, 0.1, 0.0, -0.1],   # 1번째 궤적 (ep 0)
#     [-0.6, -0.5, -0.3, -0.1, 0.0],# 2번째 궤적 (ep 10)
#     ...
# ]

for ep in range(episodes):
    position = np.random.uniform(-1.0, 1.0)
    total_reward = 0
    trajectory = []  # 각 에피소드 이동 기록

    for _ in range(50):
        state_idx = get_state_index(position)

        # ε-greedy 정책
        if random.random() < epsilon:
            action_idx = random.choice([0, 1, 2])
        else:
            action_idx = np.argmax(q_table[state_idx])

        action = action_space[action_idx]
        next_position, reward = stepFunc(position, action)
        next_state_idx = get_state_index(next_position)

        # Q 갱신
        best_next_q = np.max(q_table[next_state_idx])
        q_table[state_idx, action_idx] += alpha * (reward + gamma * best_next_q - q_table[state_idx, action_idx])

        position = next_position
        total_reward += reward
        trajectory.append(position)

    reward_list.append(total_reward)

    if ep % 10 == 0:     # 10 에피소드 마다 궤적 저장
        trajectories.append(trajectory)
    epsilon = max(0.05, epsilon * 0.995)   # epsilon 감소 (탐험 줄이기)
# trajectory	한 에피소드 안에서 위치 변화 저장
# trajectories	여러 에피소드 궤적을 모아 애니메이션용으로 저장
# reward_list	보상 흐름 확인용 (학습 성능 측정)
# q_table	Q-learning 정책 저장 (학습된 지식)

# 애니메이션 생성 (루프 밖) ----------------
# 궤적 평탄화
# 이걸 왜 따로 저장하나? 보상만 가지고는 애니메이션을 만들 수 없다.
# 실제로 에이전트가 위치를 어떻게 바꿨는지가 있어야 애니메이션이 된다.
# 그래서 trajectory 리스트를 매 에피소드마다 만들고 → trajectories에 모아서 나중에 평탄화(flat_positions) 하여 사용한다.
flat_positions = [pos for traj in trajectories for pos in traj]
frame_count = len(flat_positions)  # 애니메이션에서 몇 개의 프레임을 그릴지를 결정하는 코드
# 이 값이 왜 중요한가?
# ani = FuncAnimation(fig, update, frames=frame_count, ...)
# 이렇게 해서 update() 함수가 몇 번 호출될지를 결정한다.
# 즉 frame_count = 300이면 → 애니메이션은 300프레임으로 구성됨.
# 각 프레임은 flat_positions[frame]에서 현재 위치를 가져와 그림.


# 애니메이션 시각화 ----------
fig, ax = plt.subplots(figsize=(8, 4))   # 새로운 figure(fig)와 axes(ax)를 생성
# fig: 전체 그림 틀, ax: 좌표축이 들어가는 영역 (plot이 그려지는 공간)

ax.set_xlim(-1.1, 1.1)     # X축과 Y축 범위 설정
ax.set_ylim(-0.1, 1.05)
ax.set_title("Self-Driving Agent Simulation (Q-Learning)")
ax.set_xlabel("Position on Road (-1.0 ~ 1.0)")
ax.axvline(0, color='gray', linestyle='--', label='Center') # 세로 실선 → 회색 점선으로 중앙선 표시
point, = ax.plot([], [], 'bo', markersize=8)  # 애니메이션에 사용할 파란 점(●)을 초기 생성
ax.legend()

# 에피소드 번호를 화면에 표시할 텍스트 추가
episode_text = ax.text(0.02, 0.95, '', transform=ax.transAxes, fontsize=10)

# 애니메이션 정의 : 프레임 수만큼 호출되며, 각 프레임에서 파란 점을 업데이트
def update(frame):
    x = flat_positions[frame]   # 현재 프레임의 에이전트 위치
    y = (frame % 50) / 50     # 정규화된 스텝 위치 (y축)
    point.set_data([x], [y])     # 점 위치 업데이트
    # 에피소드 번호 계산 및 텍스트 갱신
    # 한 에피소드가 50 step으로 구성되므로, 정수 나눗셈으로 에피소드 번호 인덱스 계산
    # 사람 기준으로 에피소드 번호를 1부터 시작하게 조정 (index는 0부터 시작하니까)
    episode_num = frame // 50 + 1
    episode_text.set_text(f"Episode: {episode_num}")

    return point, episode_text  # 텍스트 객체도 반환

# FuncAnimation: update()를 frame_count만큼 반복 호출해서 애니메이션 생성
# interval=100 → 각 프레임 사이 시간 간격: 100ms,  repeat=False → 한 번만 재생 (반복 X)
ani = FuncAnimation(fig, update, frames=frame_count, interval=100, repeat=False)
plt.close(fig)    # 얘 없으면 Colab에서 fig 객체가 자동 출력되어 빈 그림이 하나 더 나옴

# 완성된 애니메이션을 HTML 형식으로 내장하여 Colab에 출력. 내부적으로 JavaScript 기반 <video>처럼 보이게 함
HTML(ani.to_jshtml())

header = f"{'state':>7}|{'-1':>7} {'0':>7} {'+1':>7}"
print(header)
print('-' * len(header))
for i, state_val in enumerate(state_space):
  q_vals = q_table[i]
  print(f'{state_val:7.2f}|{q_vals[0]:7.2f} {q_vals[1]:7.2f} {q_vals[2]:7.2f}')