# -*- coding: utf-8 -*-
"""rnn8char_toji.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktdAlTlaCCqxBccnQdusdZn7Wolcn_j4
"""

# 토지 소설을 글자 단위로 학습한 후 소설 쓰기

import tensorflow as tf
import numpy as np
import re
import urllib.request
import random

# 1) 데이터 로드
url = 'https://raw.githubusercontent.com/pykwon/etc/refs/heads/master/rnn_short_toji.txt'
with urllib.request.urlopen(url) as response:
    text = response.read().decode('utf-8')

print(text[:100])
print('텍스트 총 몇 자?', len(text))

# 2) 텍스트 정제 (한글+공백만 남김, 필요시 규칙 조정)
# text = re.sub(r"[^가-힣 ]", " ", text)
text = re.sub(r"[^가-힣 .,?!]", " ", text)  # 메모리/품질 조절용 대안
text = re.sub(r"\s{2,}", " ", text).strip()

# 고유 문자/매핑
chars = sorted(list(set(text)))
print('사용 가능한 문자 수 : ', len(chars))
char2idx = {c:i for i,c in enumerate(chars)}
idx2char = np.array(chars, dtype=object)

print(list(char2idx.items())[:5])
print(list(enumerate(chars))[:5])

# 3) 학습 시퀀스 생성 (슬라이딩 윈도우)
maxlen = 30   # 입력 길이
step = 10     # 샘플 간 간격(큼=적은 샘플=메모리↓)
sentences = []
next_chars = []

for i in range(0, len(text) - maxlen, pos_step := step):
    sentences.append(text[i:i+maxlen])
    next_chars.append(text[i+maxlen])

print('시퀀스 갯수:', len(sentences))

# 4) 벡터화 (정수 인덱스만! one-hot 생성하지 않음)
N = len(sentences)
vocab_size = len(chars)

# 입력: (N, maxlen) int32
x_idx = np.zeros((N, maxlen), dtype=np.int32)
for i, s in enumerate(sentences):
    for t, ch in enumerate(s):
        x_idx[i, t] = char2idx[ch]

# 라벨: (N,) int32 – 다음 글자의 인덱스
y_idx = np.array([char2idx[c] for c in next_chars], dtype=np.int32)

print('x_idx.shape =', x_idx.shape, ' y_idx.shape =', y_idx.shape)

# 5) 모델 구성: Embedding + LSTM + Dense
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Dropout

model = Sequential([
    Input(shape=(maxlen,)),                              # (batch, time)
    Embedding(input_dim=vocab_size, output_dim=128),     # char index -> vector (메모리 매우 절감)
    LSTM(256, return_sequences=True),
    Dropout(0.2),
    LSTM(128),
    Dropout(0.2),
    Dense(vocab_size, activation='softmax')  # 클래스 개수 = vocab_size
])

# SparseCategoricalCrossentropy: y가 one-hot이 아니라 '정수 인덱스'일 때 사용
opt = tf.keras.optimizers.RMSprop(learning_rate=0.003)   # 0.01 → 0.003 정도가 안정적
model.compile(optimizer=opt, loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=['sparse_categorical_accuracy'])
model.summary()

# 6) 학습 (정수 텐서만 배치로 메모리에 올리므로 매우 가볍습니다)
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping, ModelCheckpoint
ckpt  = ModelCheckpoint('bestmodel_sparse.keras', monitor='val_loss', save_best_only=True)
early = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

history = model.fit( x_idx, y_idx,
    batch_size=256, epochs=500, validation_split=0.05, callbacks=[ckpt, early],
    verbose=2
)

# 모델 읽기 (추론만이면 compile=False가 더 빠르고 안전)
from tensorflow.keras.models import load_model
model = load_model('bestmodel_sparse.keras', compile=False)

start_index = random.randint(0, len(text) - maxlen - 1)
seed_text = text[start_index : start_index + maxlen]

# 샘플링 & 텍스트 생성 유틸 ---------
def sample_from_probs(probs, temperature=0.7):
    probs = np.asarray(probs, dtype=np.float64)
    probs = np.maximum(probs, 1e-12)
    logits = np.log(probs) / max(temperature, 1e-8)
    logits -= np.max(logits)
    p = np.exp(logits)
    p /= p.sum()
    return np.random.choice(len(p), p=p)

def make_context_indices(seed_text, maxlen, char2idx, pad_char=' '):
    """seed 길이가 maxlen보다 짧으면 왼쪽을 pad_char로 채워 길이를 맞춤"""
    if len(seed_text) < maxlen:
        seed_text = (pad_char * (maxlen - len(seed_text))) + seed_text
    else:
        seed_text = seed_text[-maxlen:]
    # 사전에 없는 문자는 pad_char로 대체
    return np.array([char2idx.get(ch, char2idx.get(pad_char, 0)) for ch in seed_text], dtype=np.int32)

def generate_text(model, seed_text, length=400, temperature=0.7):
    """
    model : 학습/로드된 Keras 모델
    seed_text : 시작 시드 문자열 (길이가 maxlen보다 짧아도 됨)
    length : 생성할 글자 수
    temperature : 샘플링 온도 (0.5~1.2 범위에서 실험 추천)
    """
    context_idx = make_context_indices(seed_text, maxlen, char2idx, pad_char=' ')
    generated = [ch for ch in seed_text]  # 결과 누적

    for _ in range(length):
        x = context_idx[np.newaxis, :]          # (1, maxlen)
        # model 출력: (1, vocab_size)  — 마지막 LSTM의 softmax 결과
        probs = model.predict(x, verbose=0)[0]             # 확률 벡터
        next_id = sample_from_probs(probs, temperature=temperature)
        next_ch = idx2char[next_id]
        generated.append(next_ch)

        # 슬라이딩 윈도우 갱신
        context_idx = np.concatenate([context_idx[1:], [next_id]])

    return ''.join(generated)

# 실제 생성 실행 ---------
# seed_text 준비
print("\n=== 샘플 생성 ===")
print("Seed:", seed_text.replace("\n", " "))
gen = generate_text(model, seed_text, length=400, temperature=0.8)
print(gen)   # 훈련량/샘플 밀도 부족으로 결과는 불만

save_path = "generated_toji.txt"    # 저장할 파일 이름
with open(save_path, "w", encoding="utf-8") as f:
    f.write(seed_text + "\n\n")
    f.write("=== 생성 결과 ===\n")
    f.write(gen)

print(f"[완료] 결과가 '{save_path}' 파일로 저장")